### PR TITLE
openssl: Add all digest and cipher implementations

### PR DESCRIPTION
**Pull request by arteymix**

### CODE REVIEW

**Comment by nemequ** [comment]
Merged, thanks.

Do you have commit access to GNOME?  I'd be happy to grant you access to this repo, but changes need to be pushed to git.gnome.org, too…

**Comment by arteymix** [comment]
Unfortunately, I do not. I think the process is described in https://wiki.gnome.org/AccountsTeam/NewAccounts so I'll fill up the requirements.

**Comment by nemequ** [comment]
Okay.  I'll go ahead and grant you access to this repo, just don't push anything until you can push to gnome, too.  In the meantime, feel free to keep filing PRs.

**Comment by arteymix** [comment]
Thank you! I've already sent an application, so it should be a matter of time.

**Pull request merged**
