### PR TITLE
gegl: added libgegl-0.3 vapi

### PR DESCRIPTION
**Pull request by grindhold**
contributing the libgegl-bindings I generated for effector.

demo: https://github.com/grindhold/effector

### CODE REVIEW

**Comment by astavale** [comment]
Gegl does have a rule in `/gegl/Makefile.am` for building a VAPI: https://git.gnome.org/browse/gegl/tree/gegl/Makefile.am#n159

On my Fedora 23 system gegl-0.3.vapi is part of the gegl03-devel package.

If you have had to tweak this in some way it is better to submit a patch to Gegl.

**Comment by astavale** [comment]
@grindhold Nice work on effector btw.

Note that many VAPIs generated from GIRs are available in the `vala-girs` repo at https://github.com/nemequ/vala-girs/tree/master/vala/vapi. In fact gegl-0.3.vapi is already in that repo. 

I believe `vala-girs` repo is mainly used for holding GIRs ( https://github.com/nemequ/vala-girs/tree/master/gir-1.0 ) so they can be accessed when building valadoc.org. See the `update-girs` target in valadoc.org's Makefile ( https://github.com/Valadoc/valadoc-org/blob/master/Makefile ). So one thing to do would be adding Gegl to valadoc.org.

I hope that helps a bit when making future contributions.

**Comment by nemequ** [comment]
> I believe vala-girs repo is mainly used for holding GIRs ( https://github.com/nemequ/vala-girs/tree/master/gir-1.0 ) so they can be accessed when building valadoc.org.

That's a secondary reason. The primary reason is to provide a source for generating the VAPIs which are distributed with valac. Before the vala-girs repo we would run into problems where VAPIs wouldn't be updated for a *long* time because it was a pain to tell if you were using a newer or older source. With vala-girs you just grab the repo, do a jhbuild, and you know the stuff that changes are updates.

**Comment by grindhold** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=877555
a bug has been filed.

**Pull request closed without merging**
