### PR TITLE
Adds bindings for storage.h and touch.h for libmemcached.vapi.

### PR DESCRIPTION
**Pull request by arteymix**
I will write more bindings for `server.h`, `server_list.h` and other useful headers so it would be nice to keep this open until I get more substantial work in.

### CODE REVIEW

**Comment by arteymix** [comment]
I tested some of the bindings and they work real great!

`get.h` is only partially bound and `error.h` is very important, so I will work on them two and it should be good to go. Other headers provide analysis/stats

**Comment by arteymix** [comment]
@nemequ it's good to merge, binding `get.h` would require to much time (there's a whole consumable result api with fetch...), so I just fixed the binding for `get` and added `get_by_key`.

I'm pretty sure that `mget` is broken, but I'll look into it later.

**Comment by arteymix** [comment]
I did a couple of minor improvements and fixed `Memcached.Context` constructor so that we don't have to specify the length of the provided configuration.

**Comment by arteymix** [comment]
Finally, I'll be able to bind the whole thingy, so let this open for a few.

**Comment by arteymix** [comment]
I couldn't test everything, but I revised the and it's a full coverage. The only missing bindings are integration of other libraries (SASL and HashKit) and some structs which are typically accessed through functions.

**Comment by arteymix** [comment]
Just fixed and tested `Memcached.Result`. I am working on an iterator for `fetch_result`, so that we can more conveniently fetch using a `foreach` loop.

**Comment by arteymix** [comment]
```vala
context.mget ({"key1".data}, {4}, out error);
foreach (var result in context) {
    // operate on result...!
}
```

Amazing!

**Comment by nemequ** [comment]
Sorry it took me so long to get to this—I've been extremely busy for the last couple months.  Thanks for all the work, the memcached bindings look a *lot* better now.

**Comment by arteymix** [comment]
@nemequ Yes, it's clearly more complete now ;)

**Pull request merged**
