### PR TITLE
Provides binding for libmemcachedutil.h

### PR DESCRIPTION
**Pull request by arteymix**
The work here depends on #18 being merged.

### CODE REVIEW

**Comment by arteymix** [comment]
I fixed a couple of unowned and tested the pool with some real usage and it works great!

**Comment by nemequ** [comment]
Does this still need to be merged now that your other PR has been merged?

**Comment by arteymix** [comment]
@nemequ Yes, but first I will rebase this PR, otherwise you will have to resolve merge issues.

**Comment by arteymix** [comment]
@nemequ if you merge it manually, it should be a single commit.

**Comment by nemequ** [comment]
Merged, thanks.

**Pull request closed without merging**
